apiVersion: v1
kind: Pod
spec:
  containers:
#   - name: anchore
#     image: registry1.dso.mil/ironbank/anchore/engine/engine
#     imagePullPolicy: "IfNotPresent"
#     command:
#     - cat
#     tty: true
  - name: Buildah
    image: registry1.dso.mil/ironbank/opensource/containers/buildah
    imagePullPolicy: "IfNotPresent"
    command:
    - cat
    tty: true
